// <auto-generated />
using System;
using Domovoy.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domovoy.Core.Data.Migrations
{
    [DbContext(typeof(DomovoyDbContext))]
    [Migration("20260922073947_Requests")]
    partial class Requests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domovoy.Core.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FiasId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SearchText");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MaxChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MaxUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildYear")
                        .HasColumnType("integer");

                    b.Property<int?>("Entrances")
                        .HasColumnType("integer");

                    b.Property<int?>("Floors")
                        .HasColumnType("integer");

                    b.Property<int>("ManagementKind")
                        .HasColumnType("integer");

                    b.Property<int?>("ManagingOrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("ManagingOrganizationId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.DialogState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("DialogStates");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.ManagingOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Inn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ManagingOrganizations");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("BreachNotified")
                        .HasColumnType("boolean");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClarifyingOptionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeadlineDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeadlineLegalBasis")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedText")
                        .HasColumnType("text");

                    b.Property<int>("ProblemCategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<int?>("ResponsibilityZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ClarifyingOptionId");

                    b.HasIndex("ProblemCategoryId");

                    b.HasIndex("ResponsibilityZoneId");

                    b.HasIndex("Status", "DeadlineAt");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.TelemetryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("MaxUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name", "OccurredAt");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.UserBuildingLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("AppUserId", "BuildingId")
                        .IsUnique();

                    b.ToTable("UserBuildingLinks");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.CategoryResponsibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<int?>("AppliesToManagement")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsibilityZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCategoryId");

                    b.HasIndex("ResponsibilityZoneId");

                    b.ToTable("CategoryResponsibilities");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.ClarifyingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalBasis")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ProblemCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsibilityZoneId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCategoryId");

                    b.HasIndex("ResponsibilityZoneId");

                    b.ToTable("ClarifyingOptions");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.NormativeDeadline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ProblemCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCategoryId");

                    b.ToTable("NormativeDeadlines");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.ProblemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<string>("ClarifyingQuestion")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProblemCategories");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.ResponsibilityZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionHint")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ResponsibilityZones");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.Building", b =>
                {
                    b.HasOne("Domovoy.Core.Domain.Address", "Address")
                        .WithOne("Building")
                        .HasForeignKey("Domovoy.Core.Domain.Building", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Domain.ManagingOrganization", "ManagingOrganization")
                        .WithMany("Buildings")
                        .HasForeignKey("ManagingOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("ManagingOrganization");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.DialogState", b =>
                {
                    b.HasOne("Domovoy.Core.Domain.AppUser", "AppUser")
                        .WithOne("DialogState")
                        .HasForeignKey("Domovoy.Core.Domain.DialogState", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.Request", b =>
                {
                    b.HasOne("Domovoy.Core.Domain.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Domain.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Reference.ClarifyingOption", "ClarifyingOption")
                        .WithMany()
                        .HasForeignKey("ClarifyingOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domovoy.Core.Reference.ProblemCategory", "ProblemCategory")
                        .WithMany()
                        .HasForeignKey("ProblemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Reference.ResponsibilityZone", "ResponsibilityZone")
                        .WithMany()
                        .HasForeignKey("ResponsibilityZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Building");

                    b.Navigation("ClarifyingOption");

                    b.Navigation("ProblemCategory");

                    b.Navigation("ResponsibilityZone");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.UserBuildingLink", b =>
                {
                    b.HasOne("Domovoy.Core.Domain.AppUser", "AppUser")
                        .WithMany("Links")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Domain.Building", "Building")
                        .WithMany("Links")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.CategoryResponsibility", b =>
                {
                    b.HasOne("Domovoy.Core.Reference.ProblemCategory", "ProblemCategory")
                        .WithMany("Responsibilities")
                        .HasForeignKey("ProblemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Reference.ResponsibilityZone", "ResponsibilityZone")
                        .WithMany("Responsibilities")
                        .HasForeignKey("ResponsibilityZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemCategory");

                    b.Navigation("ResponsibilityZone");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.ClarifyingOption", b =>
                {
                    b.HasOne("Domovoy.Core.Reference.ProblemCategory", "ProblemCategory")
                        .WithMany("ClarifyingOptions")
                        .HasForeignKey("ProblemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Core.Reference.ResponsibilityZone", "ResponsibilityZone")
                        .WithMany()
                        .HasForeignKey("ResponsibilityZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProblemCategory");

                    b.Navigation("ResponsibilityZone");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.NormativeDeadline", b =>
                {
                    b.HasOne("Domovoy.Core.Reference.ProblemCategory", "ProblemCategory")
                        .WithMany("Deadlines")
                        .HasForeignKey("ProblemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemCategory");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.Address", b =>
                {
                    b.Navigation("Building");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.AppUser", b =>
                {
                    b.Navigation("DialogState");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.Building", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Domovoy.Core.Domain.ManagingOrganization", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.ProblemCategory", b =>
                {
                    b.Navigation("ClarifyingOptions");

                    b.Navigation("Deadlines");

                    b.Navigation("Responsibilities");
                });

            modelBuilder.Entity("Domovoy.Core.Reference.ResponsibilityZone", b =>
                {
                    b.Navigation("Responsibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
